FROM univesp.pi20250-2-s3g3-ml-base-image AS python

WORKDIR /app

RUN addgroup --system app && adduser --system --group app

COPY --chown=app:app ./src .
ENV PATH="/app/venv/bin:$PATH"

USER app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]